[package]
name = "cocotray"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "0.5.0-alpha"
gtk = "0.9.2"
dialog-box = "0.1.0"
fsio = "0.2.0"